apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: d-tursunov
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80          # Port on which the service is exposed inside the cluster
      targetPort: 5000   # Port on which the container is listening
      nodePort: 30009    # NodePort on which the service will be accessible from outside the cluster
