apiVersion: v1
kind: Service
metadata:
  name: flask-app-clusterip-service
  namespace: d-tursunov
spec:
  type: ClusterIP
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80         # Port on which the service is exposed inside the cluster
      targetPort: 5000 # Port on which the container is listening
